language: php

php:
  - '7.1'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install --dev --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_deploy:
  - bin/daux generate

deploy:
  provider: pages
  local_dir: static
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master